server:
  port: 9193
spring:
  h2:
    console:
      enabled: true
  config:
    import: configserver:http://localhost:8888
  application:
    name: notificationservice
  jpa:
    show-sql: true
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
   
order:
     defaultStoreId: 1


