server:
  port: 9192
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  config:
    import: configserver:http://localhost:8888
  application:
    name: ORDER-SERVICE
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/appservice/protocol/openid-connect/certs      
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
   
order:
  defaultStoreId: 1
  inventoryUrl : http://localhost:9191/order/{orderId}


