server:
  port: 9192
spring:
  h2:
    console:
      enabled: true
  config:
    import: configserver:http://localhost:8888
  application:
    name: ORDER-SERVICE
  jpa:
    show-sql: true
        
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/appservice/protocol/openid-connect/certs      
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
   
order:
     defaultStoreId: 1


